server:
  port: 8080
spring:
  application:
    name: Customer-Service
  datasource:
    url: jdbc:postgresql://localhost:5433/customer
    username: postgres
    password: loveable
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

rabbitmq:
  queue:
    name: customer_service
    consume: billing_service
  exchange:
    name: customer_service_exchange
  routing:
    key: customer_service_routing_key
#  docker run --rm -it -p 15672:15672 -p 5672:5672 rabbitmq:3.11.10-management